---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: rcdemapp
  name: java-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: rcdemapp
    spec:
      containers:
      - image: liontechacademy/liontechclass20:demo-v1
        name: rcdemapp
        ports:
        - name: rcdemapp
          containerPort: 80 
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: rcdemapp
  name: rcdemapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: rcdemapp