apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: liontechapps
  namespace: apps
spec:
  selector:
    matchLabels:
      app: liontechapps # has to match .spec.template.metadata.labels
  serviceName: "liontechapps"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: liontechapps # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: liontechapps
        image: liontechacademy/webapp:v1
        ports:
        - containerPort: 8080
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/liontechapps/html
  # volumeClaimTemplates:
  # - metadata:
  #     name: www
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     storageClassName: demo
  #     resources:
  #       requests:
  #         storage: 1Gi