# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: "ngnix-demo"
  namespace: qa
  labels:
    app: "ngnix-demo"
spec:
  containers:
  - name: "ngnix-demo"
    image: "emilien5/testing1:demo-v1"
    resources:
      limits:  #HPA -Horizontal port auto scaling
        cpu: 50m
        memory: 60Mi
      requests:
        cpu: 40m
        memory: 50Mi
    ports:
    - containerPort: 80
      name: http
    