apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: liontech-rs-2
  labels:
    app: rs-2
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: rs-2
  template:
    metadata:
      labels:
        app: rs-2
    spec:
      containers:
      - name: rs-2
        image: liontechacademy/liontechclass20:demo-v1
        ports:
        - name: web
          containerPort:  80
          protocol: TCP
       
       